name: flutter_errors
description: Automated Exceptions handler for Flutter development.
version: 1.0.0
homepage: https://github.com/faiyyazs/flutter-errors

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  rxdart: ^0.27.5
  sealed_annotations: ^1.13.0
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  sealed_generators: ^1.13.0
  build_runner: ^2.2.1
  analyzer: 4.7.0
